### ISSUE TITLE
[Bug] Status field being populated with field options

### ISSUE THREAD

**Issue by austensd** [fivetran/dbt_jira#60] opened 2022-06-15 17:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

After upgrading from version `>=0.8.0`, and running a full refresh of the Jira data, the `status` field on both `jira__daily_issue_field_history` and `jira__issue_enhanced` is being populated with values from the `jira.field_options` table, instead of the status id it was previously, or a value from the `jira.status` table.

### Expected behavior

I would expect the `status` field to either contain the `status_id`, or the `name` from the `jira.status` table.

### dbt Project configurations

```
version: '1.0.0'
config-version: 2
vars:
  jira:
    issue_field_history_columns: ['Work Type', 'Story Points', 'Squad']
```

### Package versions

packages:
  - package: fivetran/jira
    version: [">=0.8.0", "<0.9.0"]

### What database are you using dbt with?

redshift

### dbt Version

1.0.7

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment] 2022-06-15 17:24
Hi @austensd thanks so much for opening this issue. That definitely seems strange and something we should take a closer look at. Would you mind sharing an example or two of this behavior?

**Comment by austensd** [comment] 2022-06-15 17:35
Thanks for the quick response, here are some samples from our warehouse. 
The first image shows a sample of the `issue_id`, `status_id`, and `status` fields for some records from our `jira__issue_enhanced`
![image](https://user-images.githubusercontent.com/24901807/173889065-80651b3e-d551-4c39-9eac-bd4560d1ab1c.png)
the second shows some of the records from our `jira.status` table
![image](https://user-images.githubusercontent.com/24901807/173889180-b0484124-d148-4e27-b4a6-e9d6dbfb11fe.png)
and the third shows a sample from our `jira.field_option` table.
![image](https://user-images.githubusercontent.com/24901807/173889326-2ad8cdf3-d090-43d2-aba6-081a20d58836.png)

If we look at the `status_id` of 10035, the name from the `status` table should be `To Do`, but is instead showing as `Internet Explorer`, which is the field option that has the overlapping id. 

Hopefully this helps.

**Comment by austensd** [comment] 2022-06-15 18:33
`status` is the only field I've noticed an issue with, in terms of the other fields on the `jira__daily_issue_field_history`, we are not currently using the `sprint` field, and all of our custom fields appear to be correct. And I cannot see any issues with any other field on the `jira__issue_enhanced` table.

**Comment by fivetran-joemarkiewicz** [comment] 2022-06-15 20:21
Thanks for the update @austensd! I will be OOO the remainder of the week, but will come back to this ticket when I return on Tuesday.

**Comment by fivetran-joemarkiewicz** [comment] 2022-06-27 15:39
@austensd I just wanted to post back that I am still investigating this issue. I will be sure to post back once I identify a possible solution.

**Comment by fivetran-joemarkiewicz** [comment] 2022-08-24 14:25
Hi @austensd I apologize for the delayed response, but we think we may have identified a solution. We will start working on the fix in coming week and will share a working version of the package for you to try. If all goes well there, we can include the changes in our next release!

**Comment by jamienewcomb** [comment] 2022-09-15 11:11
Hey @fivetran-joemarkiewicz 

Noticed I am finding this issue aswell after creating some dashboards in tableau. using the same table and finding the status field being populated with random values
<img width="823" alt="Screenshot 2022-09-15 at 12 09 59" src="https://user-images.githubusercontent.com/59560169/190389276-b4855c7f-3042-4cb7-8839-97f10d49b43e.png">

How are you coming along in implementing a solution? :)

**Comment by fivetran-joemarkiewicz** [comment] 2022-09-15 13:39
Hi @jamienewcomb thanks for reaching out and sharing that you are experiencing this as well. I should have a working branch early next week that I can share for you to test out and confirm if the issue still persists.

I hope to get this fix addressed by the middle of next week.

**Comment by jamienewcomb** [comment] 2022-09-15 14:08
Thanks for the update @fivetran-joemarkiewicz 
OOI: Do you know of anyone (of where I could ask) who has managed to create a burndown chart using this table (jira__daily_issue_field_history)? Have managed everything else but struggling with this one. Thanks!

**Comment by fivetran-joemarkiewicz** [comment] 2022-09-15 19:43
Hi All,

I have been able to get a working version of the package that should address this issue. The changes are linked in the PR above. It would be great if you would be able to test the version of the package with these changes and let me know if the issue still persists. To test these changes you can use the following config in your `packages.yml`
```yml
packages:
  - git: https://github.com/fivetran/dbt_jira.git
    revision: bugfix/status-correction
    warn-unpinned: false
```
Please note this will be a breaking change since adjustments have been made to the incremental model. As such, you will need to run a `dbt run --full-refresh` in order for the changes to be reflected in your warehouse. Let me know how it goes!

Additionally, @jamienewcomb 

> Do you know of anyone (of where I could ask) who has managed to create a burndown chart using this table (jira__daily_issue_field_history)? Have managed everything else but struggling with this one. Thanks!

Unfortunately, I do not know of any current implementations of this. There may be some folks in dbt Slack that have experience putting this together!

**Comment by jamienewcomb** [comment] 2022-09-16 07:25
Thanks @fivetran-joemarkiewicz . I will pass this onto our data team and let you know if it fixes the issue

**Comment by fivetran-joemarkiewicz** [comment] 2022-09-20 21:10
@jamienewcomb and @austensd I had found an issue with the previous state of the branch I shared. However, I know feel I have been able to address it and the current build of the branch I shared above should be working as intended.

Let me know if this addresses your issues.

**Comment by jamienewcomb** [comment] 2022-09-21 11:35
Thank you @fivetran-joemarkiewicz 

It's on my data teams backlog so I am hopeful they can test this within the next week

**Comment by fivetran-joemarkiewicz** [comment] 2022-10-07 04:43
This issue has since been addressed in the latest release of the package. Feel free to upgrade the package to see the updates. If the issue still persists please reopen this issue.

**Closed by fivetran-joemarkiewicz** 2022-10-07 04:43 UTC
Labels: bug
