### ISSUE TITLE
[Bug] Current Sprint and Sprint not handling nulls well

### ISSUE THREAD

**Issue by murphymoulds-palmetto** [fivetran/dbt_jira#91] opened 2023-03-20 15:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

If an issue is removed from a sprint, it is still considering that last sprint (in history) as the `current_sprint`.

1) add issue to sprint
2) remove issue from sprint
3) run query:

```sql
select
  issue_key
  , sprint
from
  <db_name>.jira.issue_enhanced
where
  issue_key = <issue_key> 
```

![image](https://user-images.githubusercontent.com/85576814/226379525-0ead2d97-bddd-41db-aeb2-a15b38b3efda.png)

### Expected behavior

1) `current_sprint` should be null if `sprint` is null
2) `sprint` should be null if `''`

### dbt Project configurations

```yml
  # jira
  jira_database: fivetran_db
  jira_schema: jira
  jira_using_sprints: true
  jira_using_components: false
  jira_using_versions: true
  jira_include_comments: true
```

### Package versions

```yml
  - package: fivetran/jira
    version: 0.12.2
```

### What database are you using dbt with?

snowflake

### dbt Version

```console
> palm shell
Executing command `bash` in compose...
root@eeb4fa054be1:/app# dbt --version
Core:
  - installed: 1.4.5
  - latest:    1.4.5 - Up to date!
 ```

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment] 2023-03-22 16:25
Hi @murphymoulds-palmetto thanks for raising this issue! The behavior you shared where the issue being removed from a sprint should not result in the current sprint still showing as the latest sprint.

Just to confirm, when you add from sprint and remove from sprint, are you re-running the package models? I just want to make sure that this isn't caused by the need to re run the models.

**Comment by fivetran-joemarkiewicz** [comment] 2023-03-29 16:56
Thanks for sharing the clarification @murphymoulds-palmetto.

My team is currently scoping this out and will respond once we have a better understanding as to what may be occurring in this scenario and if there is a possible fix we can implement.

**Comment by fivetran-jamie** [comment] 2023-03-30 21:21
hey i think i identified the bug -- we need to use  a `left join` when joining issues with their current sprints [here](https://github.com/fivetran/dbt_jira/blob/main/models/intermediate/int_jira__issue_sprint.sql#L28) (with the inner join, null sprints are getting filtered out)

it'd be great if you had time to test this out @murphymoulds-palmetto! 
```yml
packages:
# replace any jira package lines with the following in your packages.yml
  - git: https://github.com/fivetran/dbt_jira.git
    revision: bug/null-latest-sprint
```

**Comment by murphymoulds-palmetto** [comment] 2023-03-30 23:09
> hey i think i identified the bug -- we need to use a `left join` when joining issues with their current sprints [here](https://github.com/fivetran/dbt_jira/blob/main/models/intermediate/int_jira__issue_sprint.sql#L28) (with the inner join, null sprints are getting filtered out)
> 
> it'd be great if you had time to test this out @murphymoulds-palmetto!
> 
> ```yaml
> packages:
> # replace any jira package lines with the following in your packages.yml
>   - git: https://github.com/fivetran/dbt_jira.git
>     revision: bug/null-latest-sprint
> ```

Happiness - testing now, thank you @fivetran-jamie

**Comment by fivetran-jamie** [comment] 2023-03-31 19:53
😮 very strange -- so the `time` fields here should align with the screenshot from Jira that you shared, correct? Also, just to confirm, does issue_id `23016` have issue_key `BIZOPS-242` or `BIZOPS-67`?

it sounds like it might be a connector issue, but do you possibly have multiple fields called `sprint` in your `fivetran_db.jira.field` table?

**Comment by fivetran-jamie** [comment] 2023-04-20 17:38
@murphymoulds-palmetto  friendly bump 🤠 

also, we just released a new version of the package, and I'm wondering if the updates potentially resolved your issue. could you test out v0.13.0 of the package?

**Comment by murphymoulds-palmetto** [comment] 2023-06-06 17:59
My sincere apologies @fivetran-jamie - I am going to create a ticket for someone on my team to follow up on this. I am more than happy if this is closed so that other issues are prioritized. Again, my apologies for the outlandishly late response.

**Comment by fivetran-joemarkiewicz** [comment] 2023-06-07 18:53
No worries at all @murphymoulds-palmetto! Let us know once you are able to validate this issue is no longer persisting on your end. Following, we can either keep this issue open or close it depending on your investigation. Otherwise, we can close this ticket in time.

Thanks again!

**Closed** 2023-06-14 13:43 UTC
Labels: status:in_review
