### ISSUE TITLE
Adding default column names to issue_field_history_columns causes column ambiguity in jira__issue_enhanced

### ISSUE THREAD

**Issue by ipear3** [fivetran/dbt_jira#23] opened 2021-05-06 14:47 UTC
If you add a column that exists in in the jira issue source table to the issue_field_history_columns var, it results in column ambiguity in jira__issue_enhanced.

Example columns added to issue_field_history_columns that cause column ambiguity: "Due Date", "Environment", "Issue Type", "Work Ratio".

Currently, our workaround has been to exclude jira__issue_enhanced and downstream models in order to keep our dbt run command passing

**Comment by fivetran-kristin** [comment] 2021-05-06 17:27
Hey @ipear3 thanks for bringing this to our attention. Can you share a screenshot of how you have your dbt_project.yml set up? This will help us replicate this issue.

**Comment by ipear3** [comment] 2021-05-11 12:21
Thanks @fivetran-joemarkiewicz! I've tested the `issue-pivot-updates` branch, and I can confirm it is working as intended! I have no column ambiguity when I run both `jira__daily_issue_field_history` and `jira__issue_enhanced` with some of the fields that had previously caused issue like `Issue Type` and `Work Ratio`.

Nice work! Very happy with how quickly y'all were able to resolve this :)

Any estimate when `issue-pivot-updates` will be merged? Happy to run off the branch for a while, but I'd like to remind myself when to switch back to a versioned packaged.

**Comment by fivetran-joemarkiewicz** [comment] 2021-05-11 14:19
That is great to hear @ipear3, I am glad the issue is resolved with this fix! Thank you for taking the time to test this patch on your end.

I just opened a [PR](https://github.com/fivetran/dbt_jira/pull/24) for this update; however, I will most likely wait to cut a new release of the package until I have incorporated fixes from Issue #22 and Issue #15 to the `master` branch. As such, you can most likely expect a new release by early/mid next week.

**Comment by fivetran-joemarkiewicz** [comment] 2021-05-20 20:36
@ipear3 a new version has just been cut with these changes applied: [Release v0.3.0](https://github.com/fivetran/dbt_jira/tree/v0.3.0). This should be up on the dbt hub by tomorrow.

I will close this issue, please feel free to reach back out if you have any other questions!

**Closed by fivetran-joemarkiewicz** 2021-05-20 20:36 UTC
